"""HTML-to-markdown conversion and URL fetching for documentation pages."""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from urllib.error import HTTPError, URLError
from urllib.parse import urldefrag, urljoin, urlparse
from urllib.request import Request, urlopen

import markdownify
from bs4 import BeautifulSoup
from bs4.element import Tag

from synd.builder.mdx import process_mdx
from synd.errors import FetchError

DEFAULT_USER_AGENT = "synd/0.1 (https://github.com/trydydd/synaptic-drift)"

_BOILERPLATE_TAGS = ["nav", "header", "footer", "aside", "script", "style", "noscript"]

# Theme/generator furniture that lives INSIDE <main>, where tag-based
# stripping cannot reach it. Matched against whole CSS classes, never
# substrings, so e.g. "note" or "highlight" content is untouched.
_BOILERPLATE_CSS_CLASSES = frozenset(
    {
        # Sphinx-Gallery per-example furniture: download note, download
        # links, timing line, "Gallery generated by Sphinx-Gallery" signature
        "sphx-glr-download-link-note",
        "sphx-glr-footer",
        "sphx-glr-timing",
        "sphx-glr-signature",
        # pydata-sphinx-theme "On this page" TOC sidebar
        "bd-sidebar-secondary",
    }
)

_PILCROW_RE = re.compile(r"\[¶\]\([^)]*\)|¶")


@dataclass
class FetchedHtml:
    """A raw fetched page with the response metadata the crawler needs."""

    url: str  # requested URL
    final_url: str  # URL after redirects (response.geturl())
    text: str
    content_type: str  # media type only, params stripped, lowercased


def html_to_markdown(html: str) -> str:
    """Convert a fetched HTML page to clean markdown text for chunking.

    Removes navigation, header, footer, and sidebar elements. Targets the
    main content element (<main>, <article>, or role="main") when present.
    Preserves fenced code blocks and pipe-style tables.
    """
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup.find_all(_BOILERPLATE_TAGS):
        tag.decompose()

    for tag in soup.find_all(
        class_=lambda c: c is not None and c in _BOILERPLATE_CSS_CLASSES
    ):
        tag.decompose()

    main = soup.find("main") or soup.find(role="main") or soup.find("article")
    target = str(main) if main else str(soup.body or soup)

    md = markdownify.markdownify(target, heading_style="ATX")
    md = _PILCROW_RE.sub("", md)
    md = re.sub(r"\n{3,}", "\n\n", md)
    return md.strip()


def extract_links(html: str, base_url: str) -> list[str]:
    """Extract all followable hyperlinks from an HTML page.

    Returns absolute http(s) URLs resolved against base_url, fragments
    stripped, in document order with duplicates removed. Non-navigational
    schemes (mailto:, javascript:, data:, tel:) are skipped. Scope filtering
    is the crawler's responsibility, not this function's.
    """
    soup = BeautifulSoup(html, "html.parser")
    links: list[str] = []
    seen: set[str] = set()
    for anchor in soup.find_all("a", href=True):
        if not isinstance(anchor, Tag):
            continue
        href = str(anchor["href"]).strip()
        if not href:
            continue
        scheme = urlparse(href).scheme.lower()
        if scheme and scheme not in ("http", "https"):
            continue
        resolved, _fragment = urldefrag(urljoin(base_url, href))
        if not resolved or resolved in seen:
            continue
        seen.add(resolved)
        links.append(resolved)
    return links


def fetch_text(url: str, *, user_agent: str = DEFAULT_USER_AGENT) -> str:
    """Fetch a URL and return its raw decoded text content.

    Use for plaintext index files (llms-full.txt, llms.txt) where no
    HTML-to-markdown or MDX conversion is wanted.
    Raises FetchError on HTTP error status or network failure.
    """
    req = Request(url, headers={"User-Agent": user_agent})
    try:
        with urlopen(req, timeout=30) as response:  # nosec: B310 (URL from llms.txt/caller)
            raw: str = response.read().decode("utf-8", errors="replace")
            return raw
    except HTTPError as exc:
        raise FetchError(f"HTTP {exc.code} fetching {url}") from exc
    except URLError as exc:
        raise FetchError(f"Network error fetching {url}: {exc.reason}") from exc


def fetch_html(url: str, *, user_agent: str = DEFAULT_USER_AGENT) -> FetchedHtml:
    """Fetch a URL and return the raw body plus response metadata.

    Unlike fetch_text, surfaces the response Content-Type (for gating what
    gets converted to markdown) and the post-redirect final URL (for scope
    re-checking). Does not sleep — the crawler owns request pacing.
    Raises FetchError on HTTP error status or network failure.
    """
    req = Request(url, headers={"User-Agent": user_agent})
    try:
        with urlopen(req, timeout=30) as response:  # nosec: B310 (URL from crawl frontier)
            text: str = response.read().decode("utf-8", errors="replace")
            content_type: str = response.headers.get_content_type().lower()
            final_url: str = response.geturl() or url
    except HTTPError as exc:
        raise FetchError(f"HTTP {exc.code} fetching {url}") from exc
    except URLError as exc:
        raise FetchError(f"Network error fetching {url}: {exc.reason}") from exc
    return FetchedHtml(
        url=url, final_url=final_url, text=text, content_type=content_type
    )


def fetch_page(
    url: str,
    *,
    rate_limit_sleep: float = 0.0,
    user_agent: str = DEFAULT_USER_AGENT,
) -> str:
    """Fetch a documentation page and return normalised markdown.

    Routing:
    - URL ends in .md  →  fetch text, run process_mdx(), return markdown
    - otherwise        →  fetch HTML, run html_to_markdown(), return markdown

    Uses urllib.request (stdlib) with a descriptive User-Agent header.
    Raises FetchError on HTTP error status or network failure.

    rate_limit_sleep: seconds to sleep after a successful fetch. Pass a
    nonzero value when looping over many pages to avoid hammering the server.
    """
    raw = fetch_text(url, user_agent=user_agent)

    if rate_limit_sleep > 0:
        time.sleep(rate_limit_sleep)

    if url.endswith(".md"):
        return process_mdx(raw)
    return html_to_markdown(raw)
